services:
  - type: web
    name: mini-crm-backend
    env: node
    plan: free
    buildCommand: npm install && npm rebuild sqlite3 --build-from-source
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 20.12.2
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
